import { TAX_YEAR, type TaxReturn } from "./return-types";

/** Obviously fake figures for demos and the smoke test. Not anyone's return. */
export const sampleReturn: TaxReturn = {
  taxYear: TAX_YEAR,
  personal: {
    firstName: "Alex",
    lastName: "Sample",
    ssn: "999-00-9999",
    spouseFirstName: "",
    spouseLastName: "",
    spouseSsn: "",
    street: "123 Example Avenue",
    city: "St. George",
    state: "UT",
    zip: "84770",
    occupation: "Guide",
    spouseOccupation: "",
    filingStatus: "single",
    you65OrOlder: false,
    youBlind: false,
    spouse65OrOlder: false,
    spouseBlind: false,
    homeInUs: true,
    digitalAssets: false,
    dependentsAge16OrUnder: 0,
    otherDependents: 0,
    dependentsBornThisYear: 0,
  },
  w2s: [
    {
      employer: "Sample National Park Co",
      wages: 64000,
      federalWithholding: 7200,
      socialSecurityWages: 64000,
      stateWages: 64000,
      stateWithholding: 2800,
    },
  ],
  scheduleC: {
    businessName: "Sample Canyon Tours",
    principalBusiness: "Tour operator",
    ein: "00-0000000",
    activityCode: "561500",
    accountingMethod: "Cash",
    materiallyParticipated: true,
    acquiredThisYear: false,
    grossReceipts: 18500,
    returnsAndAllowances: 0,
    advertising: 400,
    carAndTruck: 0,
    commissions: 0,
    insurance: 900,
    legalAndProfessional: 0,
    office: 250,
    supplies: 350,
    taxesAndLicenses: 0,
    travel: 800,
    deductibleMeals: 200,
    utilities: 0,
    otherExpenses: 300,
    otherDescription: "Permits and maps",
  },
  investments: {
    ordinaryDividends: 420,
    qualifiedDividends: 310,
    capitalGainDistributions: 0,
    shortTermGain: 250,
    longTermGain: 1800,
  },
  payments: {
    federalEstimated: 500,
    utahWithholdingExtra: 0,
    utahPrepayments: 0,
    stateTaxRefund: 0,
    itemizedLastYear: false,
  },
};
